def CountNucFrequency(seq):
    tempFreqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuc in seq:
        tempFreqDict[nuc] += 1
    return tempFreqDict

def qt(s):
    return str(s.count("A")), str(s.count("G")), str(s.count("C")), str(s.count("T"))

DNAstr = 'CTGCCCTACGCATGCCGTTAGTGCGGACGGCAAACCCCCGAGCACCATCCAACCTAGCGCCGACGGATCTCCCGTACTCAGATTTCGCCTCAATGCTGTCCAGATGGCATATGGTCGGATCGATTTCTCGTGAATGAACCCATTTGAAAGAAAATCCGTTATGTTAACGGATGTATAGCCTTGGAGAGAGGTAGGATTGTAGGATGTCGCGTGTCGAAGGTCAATAAAATGCAGTGACAGGACTGGTAATGACCACGCACAAATTTCAGATAAGGGACTGGGACCACGTTTAGTGTGTCAACGCGCAATTCGGAAGCCGGTAATAAGCCGTGAACGAAACAGGCTCACCTGAGTTTTGCACACCGTGCTTAATTCAGGCTGAATGGATCGGGACGGTTTCGCAAAGCTTTTTGACGATCACACCCTACAAGTGAATAACCCATGTGTGTCGTCATCTATTTTCGATGCATTCGTCTTATACCCCAGTTCCCTTCGCCGGGGTGGCTATACGAGCGCAGGGTAATCTCTTAAGCTAATGGTGGGAGGTTGAATGAGTTGTATATCGGGCCTTACAGTGTTGGCTACATGTCAACGAATACCAAACCTAAGCATATTAGCGGGGATGGTGTAACGTGCAATGTTGCAGGTCGAAGCGACGGAAGTGAAGAACCGAAATCTCAACAAGGTACGTAGATTCGCGCATCAGACACCGATGGTTTGATTGCGATTTTGATGCCCGCCCGTAGGATTTGTTAGGCTTGAGTGTGTGAATGACACCGCTGGAAGCAGCCCATCAGTCATCATGACGAGGACAAATTGATGGCTCTGCAAGCCCAGAGAGTCGGGGTGACGGCTTTTCACAACGCCTCCCTTCCGTGTGGTCCACCCAGACCACGTTTCACGCTGCTCCGCCCCATCACAGCAACTTTCACTA'
string = CountNucFrequency(DNAstr)

print(' '.join([str(value) for key, value in string.items()]))
print(' '.join((qt(DNAstr))))
